# Arrays

NumPy deals just perfect with arrays, because of
- advanced overload of `__getitem__` operator for indexing, which is handy;
- overload of other operators for comfortable shortcuts and intuitive interface;
- methods and functions implemented in `C` language, which is fast;
- rich library of functions and methods, which allows you to do almost whatever you want.

# Creating arrays

It's not so easy to create them, but it's worth it

In [1]:
from numpy import array

arr = array([1, 2, 3])
print(arr)

[1 2 3]


You just have to provide `array` constructor of `numpy` module with `iterable` type.

More examples

In [2]:
ten = array(range(10))
matrix = array([[1,2], [3, 4]])
nested_matrix = array([matrix, matrix])
strange_array = array([[1], 2])

print('Range demo:', ten)
print('Matrix demo:', matrix)
print('Array of NumPy arrays:', nested_matrix)
print('Something strange:', strange_array)

Range demo: [0 1 2 3 4 5 6 7 8 9]
Matrix demo: [[1 2]
 [3 4]]
Array of NumPy arrays: [[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]
Something strange: [[1] 2]


# Types

NumPy can be fast, because it allows you to create arrays with elements of `C` language [types](http://docs.scipy.org/doc/numpy/user/basics.types.html)

## Shorthands

Here you can see intuitive names of types to use

| Data type  | Description |
|------------|-------------|
| bool_      | Boolean (True or False) stored as a byte |
| int_       | Default integer type (same as C long; normally either int64 or int32) |
| intc       | Identical to C int (normally int32 or int64) |
| intp       | Integer used for indexing (same as C ssize_t; normally either int32 or int64) |
| float_     | Shorthand for float64. |
| complex_   | Shorthand for complex128. |

__Note__ Underscore suffix is not mandatory

## Integers

If you need to use integers of specific sizes
- use its size in bits as a suffix;
- add `u` prefix to denote `unsigned` value.

| Data type  | Description |
|------------|-------------|
| int8       | Byte (-128 to 127) |
| int16      | Integer (-32768 to 32767) |
| int32      | Integer (-2147483648 to 2147483647) |
| int64      | Integer (-9223372036854775808 to 9223372036854775807) |
| uint8      | Unsigned integer (0 to 255) |
| uint16     | Unsigned integer (0 to 65535) |
| uint32     | Unsigned integer (0 to 4294967295) |
| uint64     | Unsigned integer (0 to 18446744073709551615) |

## Floating points and complex

There is [IEEE-754](https://en.wikipedia.org/wiki/IEEE_floating_point#IEEE_754-2008) standard for floating point arithmetics, which describes format of half (16 bits), single (32 bits), double (64 bits), quadruple (128 bits) and octuple (256 bits) numbers

Standard `C` has single precision `float`, double precision `double` and additional `long double` which is at least as accurate as regular `double`

| Data type  | Description |
|------------|-------------|
| float16    | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa |
| float32    | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa |
| float64    | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa |
| complex64  | Complex number, represented by two 32-bit floats (real and imaginary components) |
| complex128 | Complex number, represented by two 64-bit floats (real and imaginary components) |

# Specify data type

NumPy `array` has a string `dtype` property to store and specify data type

In [3]:
int_array = array([1., 2.5, -0.7], dtype='int')
print('You have {0} array of type {0.dtype}'.format(int_array))

You have [1 2 0] array of type int64


Note that typecast was made automatically

NumPy will not allow you to create wrong array with specific type

In [4]:
array([[0], 1], dtype='int')

ValueError: setting an array element with a sequence.

NumPy assigned data type automatically, if it was not specified

In [5]:
arrays = [
    array([1, 2, 3]),
    array(((1, 2), (3, 4.))),
    array([[0], 1]),
    array('Hello world')
]
for a in arrays:
    print('{0.dtype}: {0}'.format(a))

int64: [1 2 3]
float64: [[ 1.  2.]
 [ 3.  4.]]
object: [[0] 1]
<U11: Hello world


Interesting thing: we explored new types!

Type `object` is used when we cannot say for sure that we have `n`-dimensional array of numbers

# Operations on arrays

You can simply apply elementwise operations

In [24]:
LENGTH = 4
a, b = array(range(LENGTH)), array(range(LENGTH, LENGTH*2))
print('Arighmetic')
print('{} +  {} = {}'.format(a, b, a + b))
print('{} *  {} = {}'.format(a, b, a * b))
print('{} ** {} = {}'.format(a, b, a ** b))
print('{} /  {} = {}'.format(a, b, a / b))
print('Binary')
print('{} ^  {} = {}'.format(a, b, a ^ b))
print('{} |  {} = {}'.format(a, b, a | b))
print('{} &  {} = {}'.format(a, b, a & b))

Arighmetic
[0 1 2 3] +  [4 5 6 7] = [ 4  6  8 10]
[0 1 2 3] *  [4 5 6 7] = [ 0  5 12 21]
[0 1 2 3] ** [4 5 6 7] = [   0    1   64 2187]
[0 1 2 3] /  [4 5 6 7] = [ 0.          0.2         0.33333333  0.42857143]
Binary
[0 1 2 3] ^  [4 5 6 7] = [4 4 4 4]
[0 1 2 3] |  [4 5 6 7] = [4 5 6 7]
[0 1 2 3] &  [4 5 6 7] = [0 1 2 3]


# Indexing

Indexing of NumPy arrays is very agile

Just look on entitites which can be used as an index
- boolean arrays;
- integer arrays;
- numbers;
- Ellipsis;
- tuples of them;
- etc.

## Integers array

You can get values from array by `iterable` (but not tuples) of indices

In [53]:
arr = array(range(10))
indices_list = [
    [1, 5, 8],
    range(1, 6, 2),
    array([8, 2, 0, -1])
]

for indices in indices_list:
    print('Indexed by {:<14}: {}'.format(str(indices), arr[indices]))

Indexed by [1, 5, 8]     : [1 5 8]
Indexed by range(1, 6, 2): [1 3 5]
Indexed by [ 8  2  0 -1] : [8 2 0 9]


## Boolean array

Boolean arrays can be result of comparison and syntax of its usage is very handy

In [64]:
arr = array(range(5))

print('Items more than 2:', arr > 2)
print(arr[arr>2])

Items more than 2: [False False False  True  True]
[3 4]


This can be read as "Give me the numbers which are greater than two"

What you actually asked for
- get elementwise comparison of array with scalar
- provide me with array of results
- fetch elements from the array, which are correspond to `True`

This means that you can use another array to get values from this one

In [61]:
a, b = array(range(0, 5)), array(range(5, 10))

print(a[b>7])

[3 4]


This gives you elements from array `a`, corresponding elements from `b` of which are greater than `7`